version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: tduser
      POSTGRES_PASSWORD: tdpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tduser -d tododb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - todo-network

  todoapi:
    image: localhost:5000/todoapi
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=tododb;Username=tduser;Password=tdpassword;"
    ports:
      - "5001:80"
    networks:
      - todo-network

  reactapp:
    image: localhost:5000/reactapp
    ports:
      - "3000:80"
    depends_on:
      - todoapi
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    networks:
      - todo-network

networks:
  todo-network:
